export const legacyPublicRoutes = [
  "/",
  "/our-practice/",
  "/our-practice/meet-the-doctor/",
  "/our-practice/meet-the-team/",
  "/blog/",
  "/book-appointment/",
  "/contact/",
  "/contact/appointment-request/",
  "/financing/",
  "/patient-information/",
  "/patient-information/new-patient-forms/",
  "/patient-information/frequently-asked-questions/",
  "/patient-information/dental-videos/",
  "/patient-information/referring-doctors/",
  "/pay-your-bill/",
  "/procedures/",
  "/review/",
  "/review/testimonials/",

  "/procedures/cleanings-prevention/",
  "/procedures/cosmetic-dentistry/",
  "/procedures/periodontal-disease/",
  "/procedures/restorations/",
  "/procedures/oral-maxillofacial-surgery/",
  "/procedures/endodontics/",
  "/procedures/pediatric-dentistry/",

  "/procedures/cleanings-prevention/digital-radiographs/",
  "/procedures/cleanings-prevention/intraoral-cameras/",
  "/procedures/cleanings-prevention/panoramic-x-rays/",
  "/procedures/cleanings-prevention/sealants/",
  "/procedures/cleanings-prevention/dental-exams-cleanings/",
  "/procedures/cleanings-prevention/dental-x-rays/",
  "/procedures/cleanings-prevention/home-care/",
  "/procedures/cleanings-prevention/how-to-properly-brush-floss/",

  "/procedures/cosmetic-dentistry/porcelain-veneers/",
  "/procedures/cosmetic-dentistry/teeth-whitening/",
  "/procedures/cosmetic-dentistry/composite-fillings/",
  "/procedures/cosmetic-dentistry/cerec/",
  "/procedures/cosmetic-dentistry/porcelain-inlays/",
  "/procedures/cosmetic-dentistry/porcelain-onlays/",

  "/procedures/periodontal-disease/causes-of-periodontal-disease/",
  "/procedures/periodontal-disease/what-is-periodontal-gum-disease/",
  "/procedures/periodontal-disease/diagnosis/",
  "/procedures/periodontal-disease/treatment/",
  "/procedures/periodontal-disease/maintenance/",

  "/procedures/restorations/crowns-bridges/",
  "/procedures/restorations/dental-implants/",
  "/procedures/restorations/dentures-partial-dentures/",
  "/procedures/restorations/root-canal-therapy-1/",

  "/procedures/oral-maxillofacial-surgery/tooth-extractions/",
  "/procedures/oral-maxillofacial-surgery/apicoectomy/",
  "/procedures/oral-maxillofacial-surgery/bone-grafting/",
  "/procedures/oral-maxillofacial-surgery/wisdom-teeth-exctractions/",

  "/procedures/endodontics/cracked-tooth/",
  "/procedures/endodontics/root-canal/",
  "/procedures/endodontics/root-canal-therapy/",
  "/procedures/endodontics/root-canal-retreatment/",

  "/what-to-expect-during-a-dental-extraction/",
  "/how-tmd-can-impact-your-overall-health/",
  "/hydrating-for-a-healthier-smile/",
  "/electric-toothbrush-for-the-best-long-term-effects/",

  "/team/dr-glenn-ashworth-dentist/",
  "/team/brandi/",
  "/team/diego/",
  "/team/erin/",
  "/team/gretchen/",
  "/team/jessica-registered-dental-hygienist/",
  "/team/rebecca/",

  "/2024/03/",
  "/2024/07/",
  "/category/cosmetic/",
  "/category/general/",
  "/category/homecare/",
  "/category/oral-surgery/",

  // Additional historical URLs surfaced by the 16-month Search Console export.
  "/eastland-landing/",
  "/team/",
  "/cosmetic-dentistry-3/",
  "/left-sidebar/",
  "/orthodontic-clinic/",
  "/author/info/",
  "/product/dental-tools/",
  "/product/floss-picks/",
  "/product/medical-gloves/",
  "/product/plastic-retainers/",
  "/product/comfort-series/",
  "/product/seriesqs/",
  "/product/colorful-brushes/",
  "/product/travel-set/",
  "/product/fresh-toothpaste/",
  "/product/oral-pro-600/",
  "/product/mint-floss/",
  "/product-category/seriespro/",
  "/product-tag/hygiene/",
  "/wishlist/",
];

export const expectedLegacyRedirects = new Map([
  ["/team/dr-glenn-ashworth-dentist/", "/our-practice/meet-the-doctor/"],
  ["/team/brandi/", "/our-practice/meet-the-team/"],
  ["/team/diego/", "/our-practice/meet-the-team/"],
  ["/team/erin/", "/our-practice/meet-the-team/"],
  ["/team/gretchen/", "/our-practice/meet-the-team/"],
  ["/team/jessica-registered-dental-hygienist/", "/our-practice/meet-the-team/"],
  ["/team/rebecca/", "/our-practice/meet-the-team/"],
  ["/2024/03/", "/electric-toothbrush-for-the-best-long-term-effects/"],
  ["/2024/07/", "/blog/"],
  ["/category/cosmetic/", "/procedures/cosmetic-dentistry/"],
  ["/category/general/", "/blog/"],
  ["/category/homecare/", "/procedures/cleanings-prevention/home-care/"],
  ["/category/oral-surgery/", "/procedures/oral-maxillofacial-surgery/"],
  ["/eastland-landing/", "/"],
  ["/team/", "/our-practice/meet-the-team/"],
  ["/cosmetic-dentistry-3/", "/procedures/cosmetic-dentistry/"],
  ["/left-sidebar/", "/blog/"],
  ["/orthodontic-clinic/", "/procedures/"],
  ["/author/info/", "/blog/"],
  ["/product/dental-tools/", "/procedures/cleanings-prevention/home-care/"],
  ["/product/floss-picks/", "/procedures/cleanings-prevention/home-care/"],
  ["/product/medical-gloves/", "/procedures/cleanings-prevention/home-care/"],
  ["/product/plastic-retainers/", "/procedures/cleanings-prevention/home-care/"],
  ["/product/comfort-series/", "/procedures/cleanings-prevention/home-care/"],
  ["/product/seriesqs/", "/procedures/cleanings-prevention/home-care/"],
  ["/product/colorful-brushes/", "/procedures/cleanings-prevention/home-care/"],
  ["/product/travel-set/", "/procedures/cleanings-prevention/home-care/"],
  ["/product/fresh-toothpaste/", "/procedures/cleanings-prevention/home-care/"],
  ["/product/oral-pro-600/", "/procedures/cleanings-prevention/home-care/"],
  ["/product/mint-floss/", "/procedures/cleanings-prevention/home-care/"],
  ["/product-category/seriespro/", "/procedures/cleanings-prevention/home-care/"],
  ["/product-tag/hygiene/", "/procedures/cleanings-prevention/home-care/"],
  ["/wishlist/", "/"],
]);
